version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always   
    expose:
      - "3308"
    ports:
      - "3308:3306"
   
    networks:
      - app-tier 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productDB
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  app:
    build:
      context: .
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    ports:
      - '3000'  
    depends_on:
      - db
    networks:
      - app-tier 



